# Site settings
title: IoT Kit for education
email: marco@marcoach.nl
description: >
  The IoT Kit for Education project is a collection of tools, frameworks, firmwares and devices that provide a consistant IoT environment.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://www.iot-kit.nl # the base hostname & protocol for your site
git_address: https://github.com/mverleun/IoT-devices
git_edit_address: https://github.com/mverleun/IoT-Web/edit/master/

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
# bootwatch: paper
#bootwatch: custom
bootwatch: spacelab

include:
  - "_headers"
# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Amsterdam
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

